make inline with magisk repo
Signed-off-by: JohnFawkes <33303104+JohnFawkes@users.noreply.github.com>

diff --git a/system/bin/font_changer b/system/bin/font_changer
--- a/system/bin/font_changer
+++ b/system/bin/font_changer
@@ -71,7 +71,7 @@ else
   BBox=false
   echo "! Busybox not detected" >> $LOG
  echo "Please install one (@osm0sis' busybox recommended)" >> $LOG
-  for applet in cat chmod cp curl grep md5sum mv printf sed sort tar tee tr unzip wget; do
+  for applet in cat chmod cp curl grep md5sum mv ping printf sed sort tar tee tr unzip wget; do
     [ "$($applet)" ] || quit 1
   done
   echo "All required applets present, continuing" >> $LOG
@@ -224,8 +224,27 @@ set_file_prop() {
 # test_connection
 # tests if there's internet connection
 test_connection() {
-  echo -n "Testing internet connection "
-  ping -q -c 1 -W 1 google.com >/dev/null 2>&1 && echo "- OK" || { echo "Error"; false; }
+  ui_print "Testing internet connection "
+  ping -q -c 1 -W 1 google.com >/dev/null 2>&1 && echo "- Internet Detected" || { echo "Error, No Internet Connection"; false; }
+}
+
+test_connection2() {
+  case "$(curl -s --max-time 2 -I http://google.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
+  [23]) echo "HTTP connectivity is up";;
+  5) echo "The web proxy won't let us through" false;;
+  *) abort "The network is down or very slow";;
+esac
+}
+
+test_connection3() {
+  wget -q --tries=5 --timeout=10 http://www.google.com -O $CACHELOC/google.idx >/dev/null 2>&1
+if [ ! -s $CACHELOC/google.idx ]
+then
+    ui_print " [!] Not Connected..[!]"
+    false
+else
+    ui_print " [-] Connected..!"
+fi
 }
 
 # Print Center
@@ -278,15 +297,15 @@ while [ "$choice" != "q" ]; do
   echo "          |--Fonts/"
   echo "              |--Custom/"
   echo -e "              ${R}|--<font-folder-name>/${N}"
-  echo -e "                       ${G}|--<font>.tff${N}"
-  echo -e "                       ${G}|--<font>.tff${N}"
+  echo -e "                       ${G}|--<font>.ttf${N}"
+  echo -e "                       ${G}|--<font>.ttf${N}"
   echo " "
   echo " You Need To Place Your Font Folders in /storage/emulated/0/Fontchanger/Fonts/Custom."
   echo " The Folder in ${R}RED${N} is Name of the Font You Want to Apply."
-  echo " This Would be the Main Folder That Holds the tff Files for That Font."
-  echo " The Files in ${G}GREEN${N} are the tff Files For That Specific Font."
+  echo " This Would be the Main Folder That Holds the ttf Files for That Font."
+  echo " The Files in ${G}GREEN${N} are the ttf Files For That Specific Font."
   echo " You Can Have Multiple Font Folders Inside the Fontchanger/Fonts Folder."
-  echo " After Creating and Placing the Correct Folders and tff Files in the Fonts Folder"
+  echo " After Creating and Placing the Correct Folders and ttf Files in the Fonts Folder"
   echo " Please Come Back to Apply the Font of Your Choice"
   echo -n "${R}Return to menu? < y | n > : ${N}"
   read -r mchoice
@@ -297,18 +316,18 @@ done
 apply_custom_font(){
 echo -e "${B}Applying Font. Please Wait...${N}"
 sleep 2
-#  cp -rf /system/etc/fonts.xml $MODPATH/system/etc/fonts.xml
-#  for i in $(find $MODPATH/system/fonts/GoogleSans-* | sed 's|.*-||'); do
-#    sed -i "s|*Roboto*$i|GoogleSans-$i|" $MODPATH/system/etc/fonts.xml
-#  done
-choice2=$(grep $choice $MODPATH/customfontlist.txt | tr -d "[$num]" | tr -d ' ')
+choice2=$(grep -w $choice $MODPATH/customfontlist.txt | tr -d "[$num]" | tr -d ' ')
 rm -rf $MODPATH/system/fonts > /dev/null 2>&1
 mkdir -p $MODPATH/system/fonts > /dev/null 2>&1
-cp -f $FCDIR/Fonts/Custom/$choice2/* $MODPATH/system/fonts > /dev/null 2>&1
-find $MODPATH/system/fonts -type f -name "$choice2*" | while read FILE ; do
-  newfile="$(echo ${FILE} |sed -e s/$choice2/Roboto/)"
-  mv "${FILE}" "${newfile}"
+mkdir -p $MODPATH/system/etc > /dev/null 2>&1
+curl -k -o "$FCDIR/Fonts/fonts.xml" https://john-fawkes.com/Downloads/xml/fonts.xml
+cp -f $FCDIR/Fonts/fonts.xml $MODPATH/system/etc
+set_perm $MODPATH/system/etc/fonts.xml 0 0 0644
+choice3=$(find $FCDIR/Fonts/Custom/ -maxdepth 1 -type f -name "*.ttf")
+for file in $FCDIR/Fonts/Custom/$choice2/*.ttf; do
+  mv "$file" "${file/$choice3/$FCDIR/Fonts/Custom/$choice2/Roboto.ttf}"
 done
+cp -f $FCDIR/Fonts/Custom/$choice2/* $MODPATH/system/fonts > /dev/null 2>&1
 set_perm_recursive $MODPATH/system/fonts 0 0 0755 0644 > /dev/null 2>&1
 truncate -s 0 $CFONT
 echo -n "CURRENT=$choice2" >> $CFONT
@@ -336,14 +355,14 @@ list_custom_fonts() {
 apply_font() {
 echo -e "${B}Applying Font. Please Wait...${N}"
 sleep 2
-#  cp -rf /system/etc/fonts.xml $MODPATH/system/etc/fonts.xml
-#  for i in $(find $MODPATH/system/fonts/GoogleSans-* | sed 's|.*-||'); do
-#    sed -i "s|*Roboto*$i|GoogleSans-$i|" $MODPATH/system/etc/fonts.xml
-#  done
-choice2=$(grep $choice $MODPATH/fontlist.txt | tr -d $choice | tr -d '[ ]' | tr -d ' ')
+choice2="$(grep -w $choice $MODPATH/fontlist.txt | tr -d '[ ]' | tr -d $choice | tr -d ' ')"
 rm -rf $MODPATH/system/fonts > /dev/null 2>&1
 mkdir -p $MODPATH/system/fonts > /dev/null 2>&1
-curl -k -o $FCDIR/Fonts/$choice2.zip https://john-fawkes.com/Downloads/$choice2.zip
+mkdir -p $MODPATH/system/etc > /dev/null 2>&1
+curl -k -o "$FCDIR/Fonts/fonts.xml" https://john-fawkes.com/Downloads/xml/fonts.xml
+cp -f $FCDIR/Fonts/fonts.xml $MODPATH/system/etc
+set_perm $MODPATH/system/etc/fonts.xml 0 0 0644
+curl -k -o "$FCDIR/Fonts/$choice2.zip" https://john-fawkes.com/Downloads/$choice2.zip
 unzip -o "$FCDIR/Fonts/$choice2.zip" 'system/*' -d $MODPATH >&2 
 set_perm_recursive $MODPATH/system/fonts 0 0 0755 0644 > /dev/null 2>&1
 truncate -s 0 $CFONT
@@ -365,9 +384,8 @@ list_fonts() {
   touch $MODPATH/fontlist.txt > /dev/null 2>&1
   for font in $fonts; do
     sleep 0.1
-    i=$(echo $font)
     num=$((num+1))
-    echo -e "[$num] $i" >> $MODPATH/fontlist.txt && echo -e "${W}[$num]${N} ${G}$i${N}"
+    echo -e "[$num] $font" >> $MODPATH/fontlist.txt && echo -e "${W}[$num]${N} ${G}$font${N}"
   done
 }
 
@@ -377,7 +395,7 @@ while [ "$choice" != "q" ]; do
   list_fonts
   break
 done
-wrong=$(cat $FCDIR/fontlist.txt | wc -l)
+wrong=$(cat $MODPATH/fontlist.txt | wc -l)
 echo -e "${G}Please Choose a Font to Apply. Enter the Corresponding Number...${N}"
 read -r choice
   case $choice in
@@ -406,7 +424,9 @@ default_menu() {
   case $choice in
       y|yes) echo "${B}Restore Default Selected...${N}"
         rm -rf $MODPATH/system/fonts
+        rm -f $MODPATH/system/etc/fonts.xml
         truncate -s 0 $CFONT
+        break
         ;;
       n|no) echo "${C}Keeping Modded Font...${N}"
         break
@@ -474,7 +494,7 @@ choice=""
     fi
     echo "${B}[-] Select an Option...${N}"
     echo " "
-    sleep 0.5
+    sleep 1
     echo -e "${W}[1]${N} ${G}- Choose From Over 200 Fonts${N}"
     echo " "
     echo -e "${W}[2]${N} ${G}- List Fonts in Folder (Custom)${N}"
